sudo: required
services:
- docker
language: rust
cache: cargo
matrix:
  include:
  - rust: stable
    env: FEATURES="--no-default-features --features base"
  - rust: beta
    env: FEATURES="--no-default-features --features base"
  - rust: nightly
    env: FEATURES="--no-default-features --features base"
  # support different python versions? https://github.com/PyO3/pyo3/blob/master/.travis.yml
before_install:
# - docker build -t aleozlx/playbook-test1 tests/test1
- docker pull aleozlx/playbook-test1
# - sudo apt-get update
# - sudo apt-get install -y python3 python3-dev
# - sudo ln -sf /usr/bin/python3 /usr/bin/python
script:
- echo === Tavis User == $(id) ====
- cargo build ${FEATURES}
- cargo test ${FEATURES}
