sudo: required
services:
- docker
language: rust
cache: cargo
matrix:
  include:
  - rust: stable
    env: FEATURES="--no-default-features --features base,ci_only" GUEST_FEATURES="ci_only"
  - rust: beta
    env: FEATURES="--no-default-features --features base,ci_only" GUEST_FEATURES="ci_only"
  - rust: nightly
    env: FEATURES="--no-default-features --features base,ci_only" GUEST_FEATURES="ci_only"
  - rust: stable
    env: FEATURES="--no-default-features --features base,ci_only" GUEST_FEATURES="ci_only,lang_python"
before_install:
- docker pull aleozlx/playbook-test:base
- docker build -t aleozlx/playbook-test:test1 --build-arg GUEST_FEATURES=${GUEST_FEATURES} tests/test1
script:
- cargo build ${FEATURES}
- cargo test ${FEATURES}
